import Foundation
import PostgresKit
import ServerLabKit

/// A `shop` schema with every index method and constraint kind: btree (composite, descending,
/// nulls last), hash, GIN (jsonb_path_ops, arrays, full text), GiST, SP-GiST, BRIN, unique
/// expression index with INCLUDE and a partial predicate; primary, composite and self-referencing
/// foreign keys (cascade, deferrable), check (one NOT VALID), unique and exclusion constraints.
///
/// Parameters: `database` (default `labdata`), `products` (rows, default 200).
struct PostgresIndexesPack: ContentPack {
    let name = "indexes-constraints"
    let version = 2
    let summary = "Every index method (btree, hash, GIN, GiST, SP-GiST, BRIN; expression, partial, covering) and constraint kind (FK, check, unique, exclusion)."

    func apply(to server: ServerEndpoint, recipe: Recipe, parameters: PackParameters, context: PackContext) async throws {
        let database = try parameters.string("database", default: PostgresDatabasePack.defaultName)
        let products = max(try parameters.int("products", default: 200), 10)
        try await PostgresSession.with(server, database: database) { client in
            _ = try await client.admin.createSchema(name: Self.schema)
            try await Self.createTables(client)
            try await Self.fill(client, products: products)
            try await Self.addConstraints(client)
            try await Self.createIndexes(client)
        }
        context.log("  shop: 6 tables, btree/hash/GIN/GiST/SP-GiST/BRIN indexes, FK/check/unique/exclusion constraints")
    }

    func verify(on server: ServerEndpoint, recipe: Recipe, parameters: PackParameters) async throws {
        let database = try parameters.string("database", default: PostgresDatabasePack.defaultName)
        let products = max(try parameters.int("products", default: 200), 10)
        let (indexes, rows) = try await PostgresSession.with(server, database: database) { client in
            (
                Set(try await client.metadata.listIndexes(schema: Self.schema, table: "products").map(\.name)),
                try await client.metadata.exactRowCount(schema: Self.schema, table: "products")
            )
        }
        let expected = ["products_name", "products_category_price", "products_sku_hash", "products_attributes",
                        "products_tags", "products_search", "products_location_gist", "products_email_lower"]
        for index in expected where !indexes.contains(index) {
            throw ServerLabError.packCheckFailed(pack: name, reason: "index \(index) is missing")
        }
        guard rows == Int64(products) else {
            throw ServerLabError.packCheckFailed(pack: name, reason: "\(rows) products, expected \(products)")
        }
    }

    static let schema = "shop"

    private static func column(_ name: String, _ type: String, nullable: Bool = true, key: Bool = false) -> PostgresColumnDefinition {
        PostgresColumnDefinition(name: name, dataType: type, nullable: nullable, primaryKey: key)
    }

    private static func createTables(_ client: PostgresClient) async throws {
        let admin = client.admin
        _ = try await admin.createTable(name: "categories", schema: schema, columns: [
            column("id", "integer", nullable: false, key: true), column("name", "text", nullable: false),
        ])
        _ = try await admin.createTable(name: "category_tree", schema: schema, columns: [
            column("id", "integer", nullable: false, key: true), column("parent_id", "integer"), column("label", "text"),
        ])
        _ = try await admin.createTable(name: "products", schema: schema, columns: [
            column("id", "integer GENERATED BY DEFAULT AS IDENTITY", nullable: false, key: true),
            column("category_id", "integer", nullable: false), column("sku", "text", nullable: false),
            column("name", "text", nullable: false), column("email", "text"), column("price", "numeric(10,2)", nullable: false),
            column("stock", "integer", nullable: false), column("attributes", "jsonb"), column("tags", "text[]"),
            column("search", "tsvector"), column("location", "point"),
        ])
        _ = try await admin.createTable(name: "order_lines", schema: schema, columns: [
            column("order_id", "integer", nullable: false), column("line_number", "integer", nullable: false),
            column("product_id", "integer", nullable: false), column("quantity", "integer", nullable: false),
        ])
        _ = try await admin.createTable(name: "bookings", schema: schema, columns: [
            column("id", "integer", nullable: false, key: true), column("room", "integer", nullable: false),
            column("during", "tstzrange", nullable: false),
        ])
        _ = try await admin.createTable(name: "events", schema: schema, columns: [
            column("at", "timestamptz", nullable: false), column("kind", "text"), column("value", "double precision"),
        ])
    }

    /// One product, every value typed (casts through postgres-wire's castLiteral).
    private static func productRow(_ index: Int) -> [PostgresInsertValue] {
        let color = ["red", "green", "blue"][index % 3]
        let email: PostgresInsertValue = index % 7 == 0 ? .null : PostgresInsertValue("Buyer\(index)@Example.com")
        return [
            PostgresInsertValue(index % 10 + 1),
            PostgresInsertValue(String(format: "SKU-%05d", index)),
            PostgresInsertValue("Product \(index)"),
            email,
            .castLiteral("\(index % 500).99", as: "numeric"),
            PostgresInsertValue(index * 7 % 1_000),
            .jsonbLiteral(#"{"color": "\#(color)", "size": \#(index % 5), "tags": ["a\#(index % 4)"]}"#),
            .castLiteral("{t\(index % 6),t\(index % 11)}", as: "text[]"),
            .castLiteral("product number \(index) quick brown fox", as: "tsvector"),
            .castLiteral("(\(index % 100),\(index / 100))", as: "point"),
        ]
    }

    private static func fill(_ client: PostgresClient, products: Int) async throws {
        let bulk = client.bulk
        _ = try await bulk.insert(into: "categories", schema: schema, columns: ["id", "name"],
                                  values: (1...10).map { [PostgresInsertValue($0), PostgresInsertValue("Category \($0)")] })
        _ = try await bulk.insert(into: "category_tree", schema: schema, columns: ["id", "parent_id", "label"],
                                  values: (1...15).map { [PostgresInsertValue($0), $0 <= 3 ? .null : PostgresInsertValue(($0 - 1) / 3), PostgresInsertValue("Node \($0)")] })
        for batch in stride(from: 1, through: products, by: 100) {
            let rows: [[PostgresInsertValue]] = (batch...min(batch + 99, products)).map(Self.productRow)
            _ = try await bulk.insert(into: "products", schema: schema,
                                      columns: ["category_id", "sku", "name", "email", "price", "stock", "attributes", "tags", "search", "location"],
                                      values: rows)
        }
        let orderLines: [[PostgresInsertValue]] = (0..<300).map { (index: Int) -> [PostgresInsertValue] in
            [PostgresInsertValue(index / 3 + 1), PostgresInsertValue(index % 3 + 1), PostgresInsertValue(index % products + 1), PostgresInsertValue(index % 5 + 1)]
        }
        _ = try await bulk.insert(into: "order_lines", schema: schema, columns: ["order_id", "line_number", "product_id", "quantity"], values: orderLines)
        let bookings: [[PostgresInsertValue]] = (1...20).map { (day: Int) -> [PostgresInsertValue] in
            let range = String(format: "[2026-01-%02d 00:00:00+00,2026-01-%02d 02:00:00+00)", day, day)
            return [PostgresInsertValue(day), PostgresInsertValue(day % 4), .castLiteral(range, as: "tstzrange")]
        }
        _ = try await bulk.insert(into: "bookings", schema: schema, columns: ["id", "room", "during"], values: bookings)
        let events: [[PostgresInsertValue]] = (0..<1_000).map { (minute: Int) -> [PostgresInsertValue] in
            let at = String(format: "2026-01-01 %02d:%02d:00+00", minute / 60 % 24, minute % 60)
            return [.castLiteral(at, as: "timestamptz"), PostgresInsertValue(["click", "view", "buy"][minute % 3]), PostgresInsertValue(Double(minute) / 3)]
        }
        _ = try await bulk.insert(into: "events", schema: schema, columns: ["at", "kind", "value"], values: events)
    }

    private static func addConstraints(_ client: PostgresClient) async throws {
        let constraints = client.constraints
        _ = try await constraints.addCompositePrimaryKey(table: "order_lines", columns: ["order_id", "line_number"], schema: schema)
        _ = try await constraints.addForeignKey(table: "products", schema: schema, column: "category_id", referencesTable: "categories",
                                                referencesColumn: "id", constraintName: "products_category_fk", onDelete: .cascade, onUpdate: .cascade)
        _ = try await constraints.addCompositeForeignKey(table: "order_lines", columns: ["product_id"], referencesTable: "products",
                                                         referencesColumns: ["id"], constraintName: "order_lines_product_fk", schema: schema,
                                                         onDelete: .restrict, deferrable: true, initiallyDeferred: true)
        _ = try await constraints.addForeignKey(table: "category_tree", schema: schema, column: "parent_id", referencesTable: "category_tree",
                                                referencesColumn: "id", constraintName: "category_tree_parent_fk", onDelete: .setNull)
        _ = try await constraints.addCheckConstraint(table: "products", schema: schema, condition: "price >= 0", constraintName: "products_price_check")
        _ = try await constraints.addCheckConstraintNotValid(table: "products", condition: "stock <= 100000",
                                                             constraintName: "products_stock_check", schema: schema)
        _ = try await constraints.addUniqueConstraint(table: "products", schema: schema, columns: ["sku"], constraintName: "products_sku_unique")
        _ = try await constraints.addExclusionConstraint(table: "bookings", using: "gist", elements: [(column: "during", operator: "&&")],
                                                         constraintName: "bookings_no_overlap", schema: schema)
    }

    private static func createIndexes(_ client: PostgresClient) async throws {
        let indexes = client.indexes
        _ = try await indexes.createIndex(name: "products_name", table: "products", schema: schema, columns: ["name"])
        _ = try await indexes.createAdvancedIndex(name: "products_category_price", table: "products", schema: schema, columns: [
            PostgresIndexColumn(name: "category_id"), PostgresIndexColumn(name: "price", order: .desc, nullsOrder: .last),
        ])
        _ = try await indexes.createAdvancedIndex(name: "products_sku_hash", table: "products", schema: schema,
                                                  columns: [PostgresIndexColumn(name: "sku")], indexType: .hash)
        _ = try await indexes.createAdvancedIndex(name: "products_attributes", table: "products", schema: schema,
                                                  columns: [PostgresIndexColumn(name: "attributes", operatorClass: "jsonb_path_ops")], indexType: .gin)
        _ = try await indexes.createAdvancedIndex(name: "products_tags", table: "products", schema: schema,
                                                  columns: [PostgresIndexColumn(name: "tags")], indexType: .gin)
        _ = try await indexes.createAdvancedIndex(name: "products_search", table: "products", schema: schema,
                                                  columns: [PostgresIndexColumn(name: "search")], indexType: .gin)
        _ = try await indexes.createAdvancedIndex(name: "products_location_gist", table: "products", schema: schema,
                                                  columns: [PostgresIndexColumn(name: "location")], indexType: .gist)
        _ = try await indexes.createAdvancedIndex(name: "products_location_spgist", table: "products", schema: schema,
                                                  columns: [PostgresIndexColumn(name: "location")], indexType: .spgist)
        _ = try await indexes.createAdvancedIndex(name: "products_email_lower", table: "products", schema: schema,
                                                  columns: [PostgresIndexColumn(expression: "lower(email)")], unique: true,
                                                  include: ["name"], whereClause: "email IS NOT NULL")
        _ = try await indexes.createAdvancedIndex(name: "events_at_brin", table: "events", schema: schema,
                                                  columns: [PostgresIndexColumn(name: "at")], indexType: .brin)
    }
}
